version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.6.3-jdk-8
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline
      - run:
          name: Build and Test
          command: mvn clean verify

